GePeTinho/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
import re
from myapp import views
from django.views.generic import TemplateView



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
    path('social-auth/', include('social_django.urls', namespace='social-auth')),
]

myapp/urls.py
from django.urls import path,include
from . import views
from django.contrib.auth import views as auth_views

app_name = 'myapp'

urlpatterns = [
    path('chat/<int:chat_id>/', views.chat_view, name='chat_view'),
    path('create_chat/', views.create_chat, name='create_chat'),
    path('create_msg/', views.create_msg, name='create_msg'),
    path('clear_chat/', views.clear_chat, name='clear_chat'),
    path('delete_chat/', views.delete_chat, name='delete_chat'),
    path('', views.index, name='index'),
    path('index/', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', views.logout, name='logout'),
    path('accounts/', include('allauth.urls')),
]

myapp/models.py
from django.db import models
from django.contrib.auth.models import User


class Chat(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        ordering = ('created_at', )

    def __str__(self):
        return str(self.pk)


class Message(models.Model):
    chat = models.ForeignKey(Chat, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    sender = models.TextField(max_length=10)
    content = models.TextField()
    typeofMessage = models.TextField(default='text')

    class Meta:
        ordering = ('created_at', )

    def __str__(self):
        return self.content

myapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .models import Chat, Message
from django.urls import reverse
import requests
from urllib.parse import urljoin
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import logout as auth_logout


def login(request):
    return render(request, 'login.html')


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('myapp:login'))  # Redirect to the login page after successful sign-up
    else:
        form = UserCreationForm()
    return render(request, 'signup.html', {'form': form})


@login_required
def logout(request):
    if request.method == 'POST':
        auth_logout(request)
        return redirect(reverse('myapp:login'))
    else:
        return redirect(reverse('myapp:index'))

@login_required
def index(request):
    user = request.user  # Retrieve the logged-in user
    chats = Chat.objects.all()
    context = {'chats': chats, 'user': user}  # Add 'user' to the context
    return render(request, 'index.html', context)


@login_required
def chat_view(request, chat_id):
    chats = Chat.objects.all()
    chat = Chat.objects.get(pk=chat_id)
    messages = Message.objects.filter(chat=chat)
    context = {'chats': chats, 'chat': chat, 'messages': messages}
    return render(request, 'chat_detail.html', context)


@login_required
def create_chat(request):
    if request.method == 'POST':
        user = request.user  # Retrieve the logged-in user
        chat = Chat.objects.create(user = user)
        return redirect(reverse('myapp:chat_view', kwargs={'chat_id': chat.pk}))
    else:
        return render(request, 'create_chat.html')


@login_required
def create_msg(request):
    if request.method == 'POST':
        chat_id = request.POST.get('chat_id')
        chat_input = request.POST.get('chat_input')
        sender = 'user'
        typeofMessage = 'text'

        # Retrieve the chat object based on chat_id
        chat = Chat.objects.get(pk=chat_id)

        # Create the message object with the provided data
        Message.objects.create(chat=chat, content=chat_input, sender=sender, typeofMessage=typeofMessage)

        # Fetch the JSON data from the URL
        response = requests.get('https://cataas.com/cat/gif?json=true')
        json_data = response.json()

        # Extract the image URL from the JSON data
        base_url = 'https://cataas.com'
        image_url = json_data['url']

        Message.objects.create(chat=chat, content=urljoin(base_url, image_url), sender="system", typeofMessage='img_url')
        Message.objects.create(chat=chat, content="Meow Meow Moew", sender="system", typeofMessage=typeofMessage)

        return redirect(reverse('myapp:chat_view', kwargs={'chat_id': chat.pk}))
    else:
        return render(request, 'create_msg.html')


@login_required
def clear_chat(request):
    if request.method == 'POST':
        chat_id = request.POST.get('chat_id')
        # Retrieve the chat object based on chat_id
        chat = Chat.objects.get(pk=chat_id)
        # Delete the messages with the matching chat_id
        Message.objects.filter(chat_id=chat.pk).delete()

        return redirect(reverse('myapp:chat_view', kwargs={'chat_id': chat.pk}))
    else:
        return render(request, 'create_chat.html')


@login_required
def delete_chat(request):
    if request.method == 'POST':
        chat_id = request.POST.get('chat_id')
        # Retrieve the chat object based on chat_id
        chat = Chat.objects.get(pk=chat_id)
        # Delete the messages with the matching chat_id
        chat.delete()

        return redirect(reverse('myapp:index'))
    else:
        return render(request, 'create_chat.html')

myapp/templates/base.html
<!-- base.html -->
<!DOCTYPE html>
<html>
<head>
  <title>GePeTinho</title>
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
  <script src="{% static 'js/script.js' %}"></script>
</head>
<body>
  <div class="sidebar">
    <h2>GePeTinho WEB</h2>
    <form method="POST" action="{% url 'myapp:create_chat' %}">
      {% csrf_token %}
    <button type="submit" class="new-chat-btn">+New Chat</button>
    </form>
    <ul class="chat-list">
      {% for chat in chats %}
        {% if user == chat.user %}
         <li><a href = '/chat/{{chat.id}}'>Chat {{chat.id}}</a></li>
          {% endif %}
      {% endfor %}
    </ul>
    <div class="settings">
      <hr class="my-line">
        <form method="POST" action="{% url 'myapp:clear_chat' %}">
          {% csrf_token %}
          <input type="hidden" name="chat_id" value="{{ chat.pk }}">
          <button type="submit" class="clear">Limpar conversas</button>
        </form>

      <form method="POST" action="{% url 'myapp:delete_chat' %}">
          {% csrf_token %}
          <input type="hidden" name="chat_id" value="{{ chat.pk }}">
          <button type="submit" class="clear">Deletar chat</button>
        </form>

      <a href="#" class="config">Configurações</a>

      <form method="POST" action="{% url 'myapp:logout' %}">
      {% csrf_token %}
    <button type="submit" class="clear">Logout</button>
    </form>

    </div>
  </div>

    <div class="chat-detail-container">
    {% block content %}
    {% endblock %}
  </div>

  <div id="settings-popup">
    <form>
      <label for="theme-light">Light Theme</label>
      <input type="radio" name="theme" id="theme-light" value="light">

      <label for="theme-dark">Dark Theme</label>
      <input type="radio" name="theme" id="theme-dark" value="dark">

      <button type="submit">Apply</button>
    </form>
  </div>
</body>
</html>

myapp/templates/chat_detail.html
<!-- chat_detail.html -->

{% extends 'base.html' %}

{% block content %}
<div class="chat">
  <div class="chat-header">
    <h3>Chat {{ chat.pk }}</h3>
  </div>
  <div class="chat-messages">
      {% for message in messages %}
      {% if message.sender == 'user' %}
      <div class="message-container user-message"><p>Usuário: {{ message.content }}</p></div>
      {% else %}
          {% if message.typeofMessage == 'img_url' %}
          <div class="message-container system-message"><img src="{{ message.content }}"></div>
          {% else %}
          <div class="message-container system-message"><p>GePeTinho: {{ message.content }}</p></div>
          {% endif %}
      {% endif %}
      {% endfor %}
  </div>
  <div class="chat-container">
    <form method="POST" action="{% url 'myapp:create_msg' %}">
      {% csrf_token %}
    <input type="text" name="chat_input" id="chat_input" class="chat_input"  placeholder="Digite sua mensagem aqui..." required>
    <input type="hidden" name="chat_id" value="{{ chat.pk }}">
    <button type="submit" class="send-button">Send</button>
    </form>

  </div>
</div>
{% endblock %}

myapp/templates/index.html
<!-- index.html -->
{% extends 'base.html' %}

{% block content %}

<div class="greeting">
  <h2>Welcome to GePeTinho WEB</h2>
  <p>Please select between:</p>
  <p>Creating a new chat</p>
  <p>Select an existing chat</p>
</div>

{% endblock %}

myapp/templates/login.html
<!DOCTYPE html>
<html>
<head>
  <title>Login Page</title>
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
  <script src="https://apis.google.com/js/platform.js" async defer></script>
  <style>
    body {
      background-color: black;
      color: white;
    }
  </style>
</head>
<body>
  <div class="login-container">
    <h2>Login</h2>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Login</button>
    </form>
    <button type="button" class="btn btn-primary btn-google">
      <i class="fa fa-google"></i>
      <a class="white" href="{% url 'social:begin' 'google-oauth2' %}">
        Login com Google
      </a>
    </button>
    <button type="button" class="btn btn-primary btn-signup">
      <a class="white" href="{% url 'myapp:signup' %}">Sign Up</a>
    </button>
  </div>
</body>
</html>

myapp/templates/signup.html
<!DOCTYPE html>
<html>
<head>
  <title>Sign Up</title>
  {% load static %}
  {% load socialaccount %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
</head>
  <style>
    body {
      background-color: black;
      color: white;
    }
  </style>
<body>
  <div class="signup-container">
    <h2>Sign Up</h2>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Sign Up</button>
    </form>
  </div>
</body>
</html>